---
abstract: 'Simple routine to return the ISO 8601 week of the year (as well as the ISO week year)'
author:
  - 'Greg George, IT Technology Solutions P/L, Australia, gng@cpan.org'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-WeekOfYear
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  Time::Local: 0
  perl: 5.006
version: 1.06
